-- 코드를 입력하세요



SELECT PR.PRODUCT_CODE, SUM(PR.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT AS PR, OFFLINE_SALE AS OS
WHERE PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PR.PRODUCT_CODE ASC;