-- CAR_RENTAL_COMPANY_CAR: 자동차 정보
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: 자동차 대여 기록 정보
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN: 자동차 종류 별 대여 기간 종류 별 할인 정책 정보

-- 11월에 대여 가능한 세단, SUV 데이터 집합
WITH RENTAL_POSSIBLE_CAR AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        -- WHERE START_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30')
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
    AND CAR_TYPE IN ('세단', 'SUV')
),
-- 세단, SUV 30일 대여시 할인 정책
DISCOUNT_PLAN AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV')
    AND DURATION_TYPE = '30일 이상'
)
SELECT A.CAR_ID AS CAR_ID, A.CAR_TYPE AS CAR_TYPE, TRUNCATE(A.DAILY_FEE * 30 * (1 - B.DISCOUNT_RATE / 100), 0) AS FEE
FROM RENTAL_POSSIBLE_CAR A
JOIN DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.DAILY_FEE * 30 * (1 - B.DISCOUNT_RATE / 100) >= 500000 -- 할인율 적용된 30일 대여 가격이 50 이상
AND A.DAILY_FEE * 30 * (1 - B.DISCOUNT_RATE / 100) < 2000000 -- 할인율 적용된 30일 대여 가격이 200 미만
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;