WITH FH AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
),
J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FH.FLAVOR
FROM FH
JOIN J
ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.TOTAL + J.TOTAL) DESC
LIMIT 3;

